{% set name = "cyrsoxs" %}
{% set version = "1.1.5.17" %}
{% set sha = "e8eadf08cba602b6b6aa84da8521f28bee12f6558fefceba98b6b7bf220f4d18" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pbeaucage/cyrsoxs/archive/refs/tags/V{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  skip: True  # [py<37]
  skip: True  # [not linux64 and not win64]
  skip: True  # [cuda_compiler_version == "None"]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make
    - libgomp
  host:
    - python
    - pybind11
    - pybind11-abi
    - hdf5
    - libgomp
    - libconfig
  run:
    - libgomp
    - libconfig
    - python
test:
  imports:
    - CyRSoXS
about:
  home: https://github.com/usnistgov/cyrsoxs
  summary: 'Cy-RSoXS Forward Simulator for Resonant Soft X-Ray Scattering'
  description: |
  license: MIT
  license: NIST-PD
  license_family: MIT
  license_file: LICENSE
  doc_url: https://nrss.readthedocs.io/
  dev_url: https://github.com/usnistgov/cyrsoxs

extra:
  recipe-maintainers:
    - pbeaucage
    - pdudenas
